config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    resources :admintools, only: :index do
      post :clear, on: :collection
      post 'addrows', on: :collection
      post 'upload', on: :collection
      post 'upload_yaml', on: :collection
      get 'download', on: :collection
      get 'download_full', on: :collection
    end
    devise_for :users, :controllers => { invitations: 'invitations'}
    resources :entity_instances do 
      get :autocomplete, on: :collection
      get :autocomplete_type, on: :collection
      get :preview
      
    end
    resources :users

    resources :suggest_relationships

    resources :admintools
    
    resources :relationships do
      resources :relationship_bits
      get :autocomplete_type, on: :collection
      get :preview
    end

    resources :searches do
      get :search_history, on: :collection
      get :search, on: :collection
      get :root, on: :collection
      get :load_info, on: :member
    end

    get '*unmatched_route', to: 'application#raise_not_found'

  end
  root 'searches#root'

  get '/:locale' => 'searches#root'
 
  

end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  entity_instance_to   :integer
#  entity_instance_from :integer
#  created_at           :datetime
#  updated_at           :datetime
#  relationship_type_id :integer
#  rel_node_id          :string(255)
#  user_id              :integer
#

class Relationship < ActiveRecord::Base

  require 'neo4j-core'

  belongs_to :entity_to, :class_name => "EntityInstance", :foreign_key => "entity_instance_to"
  belongs_to :entity_from, :class_name => "EntityInstance", :foreign_key => "entity_instance_from"
  has_many :relationship_bits, dependent: :destroy

  
  belongs_to :relationship_type, :class_name => "RelationshipType", :foreign_key => "relationship_type_id"

  paginates_per 5

  belongs_to :user

  after_update :update_neo4j_relationship
  after_create :create_neo4j_relationship
  before_destroy :destroy_neo4j_relationship

  private
    def destroy_neo4j_relationship
      unless rel_node_id.nil?
        Neo4j::Relationship.load(rel_node_id).del
      end
    end

    def create_neo4j_relationship
      node_from = Neo4j::Node.load(entity_from.node_id) #Neo4j::Node.create
      node_to = Neo4j::Node.load(entity_to.node_id)
      rel_type = relationship_type
      node_rel = node_from.create_rel(rel_type.name, node_to)
      update_column(:rel_node_id, node_rel.neo_id)
    end

    def update_neo4j_relationship
      destroy_neo4j_relationship
      create_neo4j_relationship
    end
end

app/models/relationship_type.rb
# == Schema Information
#
# Table name: relationship_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class RelationshipType < ActiveRecord::Base
  
  searchkick text_start: ['name']
  has_many :relationships
  validates_uniqueness_of :name

end

app/controllers/relationships_controller.rb
require 'neo4j-core'


class RelationshipsController < ApplicationController
  authorize_resource
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]
  before_action :init_neo4j_session, only: [:create, :update]
  include Graphstorage


  def new 
    @relationship = Relationship.new
  
  end
  
  def create
    @relationship = Relationship.new(relationship_params)
    @relationship.user = current_user
    @relationship.relationship_type = RelationshipType.find_or_create_by(name: params[:relationship][:relationship_type])
        
    if @relationship.save

      redirect_to @relationship
    else 
      render 'new'
    end 
  end

  def destroy

    @relationship.destroy
    
    redirect_to relationships_path
  end
  
  def show
  end
  
  def index
    @relationships = Relationship.all.page(params[:page])
  end

  def preview
    @relationship = Relationship.find(params[:relationship_id])
  end
  
  def update
    
    #@entity_instance_to = EntityInstance.find(params["entity_instance_to"])
    #@entity_instance_from = EntityInstance.find(params["entity_instance_from"])
    #@relationship.entity_instance_to = @entity_instance_to
    #@relationship.entity_instance_from = @entity_instance_from
    
    @relationship.relationship_type = RelationshipType.find_or_create_by(name: params[:relationship][:relationship_type])
    if @relationship.update(relationship_params)
      redirect_to @relationship
    else
      render 'edit'
    end
  end

  def edit
    @type = @relationship.relationship_type.name
  end

  def autocomplete_type
    @results = RelationshipType.search(params[:query], fields: [:name], limit: 10).results 
    @results = RelationshipType.where("name like ?", "%#{params[:query]}%").limit(10) if @results.empty?
    render json: @results
  end
  
  private

    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    def relationship_params
      params.require(:relationship).permit(:name, :description, :entity_instance_from, :entity_instance_to, :relationship_type_id)
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.haml
= form_for @relationship, :html => { :class => "form-horizontal" } do |f|
  - if @relationship.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      %h2
        = pluralize(@relationship.errors.count, "error")
        prohibited
        this relationship from being saved:
      %ul
        - @relationship.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, t('relationships.attributes.name'), :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, :class => "form-control"
  .form-group
    = f.label :entity_instance_to, t('relationships.attributes.entity_instance_to'), :class => "col-sm-2 control-label"
    .col-sm-10
      = text_field_tag 'entity_to', nil, placeholder: t('relationships.entity_placeholder'), :class => "form-control typeahead", data: 'relationship_entity_instance_to'
      = f.text_field(:entity_instance_to, :class => "form-control hidden")
  .form-group
    = f.label :entity_instance_from, t('relationships.attributes.entity_instance_from'), :class => "col-sm-2 control-label"
    .col-sm-10
      = text_field_tag 'entity_from', nil, placeholder: t('relationships.entity_placeholder'), :class => "form-control typeahead", data: 'relationship_entity_instance_from'
      = f.text_field(:entity_instance_from, :class => "form-control hidden")
  .form-group
    = f.label :relationship_type, t('relationships.attributes.type'), :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :relationship_type, class: "form-control", value: @type
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"
:javascript
  var engine_entity = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {"url":'/entity_instances/autocomplete?query=%QUERY'}
  });
  var engine_type = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {"url":'/relationships/autocomplete_type?query=%QUERY'}
  });

  engine_entity.initialize();
  engine_type.initialize();

  $(".typeahead").typeahead({
    "highlight": true
  },
  {
    minLength: 1,
    name: 'dataset',
    displayKey: 'name',
    "source": engine_entity.ttAdapter()
  }).on('typeahead:selected', function (obj, datum) {
    $("#" + $(this).attr('data')).val(datum.id);
    console.log($(this).attr('data'))
  });
  $("#relationship_relationship_type").typeahead({
    "highlight": true
  },
  {
    minLength: 1,
    name: 'dataset',
    displayKey: 'name',
    "source": engine_type.ttAdapter()
  })

app/views/relationships/edit.html.haml
%h1= t('helpers.edit') + ' ' + t('relationships.model_name')
= render 'form'
= link_to t('helpers.back'), relationship_path(@relationship)

app/views/relationships/index.html.haml
%h1= t('relationships.models_name')
%table.table
  %tr
    %th= t('relationships.attributes.name')
    %th= t('relationships.attributes.entity_instance_to')
    %th= t('relationships.attributes.entity_instance_from')
    %th
    %th
  - @relationships.each do |relationship|
    %tr
      %td=link_to relationship.name, relationship_path(relationship)
      %td= link_to relationship.entity_to.name, relationship.entity_to
      %td= link_to relationship.entity_from.name, relationship.entity_from
      -if can? :manage, Relationship
        %td= link_to t('helpers.edit'), edit_relationship_path(relationship)
        %td= link_to t('helpers.destroy'), relationship_path(relationship), |
          method: :delete, data: { confirm: 'Are you sure?' } |
= paginate @relationships
= link_to t('relationships.new'), new_relationship_path if can? :manage, Relationship

app/views/relationships/new.html.haml
%h1= t('relationships.new')
= render 'form'
= link_to t('helpers.back'), relationships_path

app/views/relationships/preview.html.haml
.page-header
  %h1= t('relationships.model_name')
%dl.dl-horizontal
  %dt= t('relationships.attributes.name')
  %dd= @relationship.name
  %dt= t('relationships.attributes.entity_instance_to')
  %dd= @relationship.entity_to.name
  %dt= t('relationships.attributes.entity_instance_from')
  %dd= @relationship.entity_from.name
  %dt= t('relationships.attributes.type')
  %dd= @relationship.relationship_type.name
.page-header
  = link_to relationship_relationship_bits_path(@relationship), :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    = t('relationship_bits.models_name')
  %h1= t('relationship_bits.models_name')
= render @relationship.relationship_bits

app/views/relationships/show.html.haml
.page-header
  = link_to relationships_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    = t('helpers.back')
  -if can? :manage, Relationship
    = link_to edit_relationship_path(@relationship), :class => 'btn btn-primary' do
      %span.glyphicon.glyphicon-pencil
      = t('helpers.edit')
  %h1= t('relationships.model_name')
%dl.dl-horizontal
  %dt= t('relationships.attributes.name')
  %dd= @relationship.name
  %dt= t('relationships.attributes.entity_instance_to')
  %dd= @relationship.entity_to.name
  %dt= t('relationships.attributes.entity_instance_from')
  %dd= @relationship.entity_from.name
  %dt= t('relationships.attributes.type')
  %dd= @relationship.relationship_type.name
.page-header
  = link_to relationship_relationship_bits_path(@relationship), :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    = t('relationship_bits.models_name')
  %h1= t('relationship_bits.models_name')
= render @relationship.relationship_bits