config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    resources :admintools, only: :index do
      post :clear, on: :collection
      post 'addrows', on: :collection
      post 'upload', on: :collection
      post 'upload_yaml', on: :collection
      get 'download', on: :collection
      get 'download_full', on: :collection
    end
    devise_for :users, :controllers => { invitations: 'invitations'}
    resources :entity_instances do 
      get :autocomplete, on: :collection
      get :autocomplete_type, on: :collection
      get :preview
      
    end
    resources :users

    resources :suggest_relationships

    resources :admintools
    
    resources :relationships do
      resources :relationship_bits
      get :autocomplete_type, on: :collection
      get :preview
    end

    resources :searches do
      get :search_history, on: :collection
      get :search, on: :collection
      get :root, on: :collection
      get :load_info, on: :member
    end

    get '*unmatched_route', to: 'application#raise_not_found'

  end
  root 'searches#root'

  get '/:locale' => 'searches#root'
 
  

end

app/models/entity_instance.rb
# == Schema Information
#
# Table name: entity_instances
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  description    :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  node_id        :string(255)
#  entity_type_id :integer
#  user_id        :integer
#

class EntityInstance < ActiveRecord::Base

  include Rails.application.routes.url_helpers
  require 'neo4j-core'
  include SearchHelper

  searchkick text_start: ['name']

  validates :name, presence: true,
                    length: { minimum: 1 }
                    
  paginates_per 5
  
  has_many :relationships_from, :class_name => "Relationship", :foreign_key => "entity_instance_from"
  has_many :relationships_to, :class_name => "Relationship", :foreign_key => "entity_instance_to"
  
  belongs_to :entity_type
  belongs_to :user

  after_update :update_node
  after_create :create_node
  before_destroy :destroy_relationship, :destroy_graph_entities

  # def encode_with(coder)
  #   coder['name'] = @name
  #   coder['description'] = @description
  #   coder['created_at'] = @created_at
  #   coder['updated_at'] = @updated_at
  #   coder['entity_type_id'] = @entity_type_id
  #   coder['user_id'] = @user_id
  # end

  # def init_with(coder)
  #   @name = coder['name']
  #   @description = coder['description']
  #   @created_at = coder['created_at']
  #   @updated_at = coder['updated_at']
  #   @entity_type_id = coder['entity_type_id']
  #   @user_id = coder['user_id']
  # end

  def self.search_for_graph(search)
  	search(search).results.first || where("name like ?", "%#{search}%").first
  end

  def parse_info
    info = Hash.new
    info[:link] = entity_instance_path(id) + '/preview'
    info[:name] = ERB::Util.html_escape(name)
    info[:description] = ''
    if description
      info[:description] = description unless description.empty?
    end
    info
  end

  def delete_label
    node = Neo4j::Node.load(node_id)
    node.remove_label(entity_type.name)
  end

  private
    def update_node
      Neo4j::Session.create_session(:server_db, "http://localhost:7474")
      node = Neo4j::Node.load(node_id)
      node.props = {entity_id: id, name: name, description: description}
      node.set_label(entity_type.name)
    end

    def create_node
      Neo4j::Session.create_session(:server_db, "http://localhost:7474")
      node = Neo4j::Node.create({entity_id: id, name: name, description: description })
      node.set_label(entity_type.name)
      update_column(:node_id, node.neo_id)
    end

    def destroy_relationship
      relationships_to.destroy_all
      relationships_from.destroy_all
    end

    def destroy_graph_entities
      unless node_id.nil?
        Neo4j::Node.load(node_id).del
      end 
    end

end

app/controllers/entity_instances_controller.rb
require 'neo4j-core'

class EntityInstancesController < ApplicationController
  authorize_resource
  before_action :set_entity_instance, only: [:show, :edit, :update, :destroy, :load_info]
  before_action :init_neo4j_session, only: [:create, :update]
  before_action :delete_old_label, only: :update

  def new 
    @entity_instance = EntityInstance.new
  
  end
  
  def create
    @entity_instance = EntityInstance.new(entity_instance_params)
    @entity_instance.user = current_user
    @entity_instance.entity_type = EntityType.find_or_create_by(name: params[:entity_instance][:entity_type])
    
    if @entity_instance.save
      redirect_to @entity_instance
    else
      render 'new'
    end
    
  end
  
  def nodes
    render 'new'
  end
  
  def destroy
    @entity_instance.destroy
    
    redirect_to entity_instances_path
  end
  
  def update
    @entity_instance.entity_type = EntityType.find_or_create_by(name: params[:entity_instance][:entity_type])
    if @entity_instance.update(entity_instance_params)
      redirect_to @entity_instance
    else
      render 'edit'
    end
  end

  def edit
    @type = @entity_instance.entity_type.name
  end
  
  def show
    @entity_type = @entity_instance.entity_type
  end

  def preview
    @entity_instance = EntityInstance.find(params[:entity_instance_id])
    @entity_type = @entity_instance.entity_type
  end
  
  def index
    @entity_instances = EntityInstance.all.page(params[:page])
  end

  def autocomplete
    @results = EntityInstance.search(params[:query], fields: [:name], limit: 10).results
    @results = EntityInstance.where("name like ?", "%#{params[:query]}%").limit(10) if @results.empty?
    render json: @results
  end

  def autocomplete_type
    @results = EntityType.search(params[:query], fields: [:name], limit: 10).results 
    @results = EntityType.where("name like ?", "%#{params[:query]}%").limit(10) if @results.empty?
    render json: @results
  end
  
  private

    def set_entity_instance
      @entity_instance = EntityInstance.find(params[:id])
    end

    def entity_instance_params
      params.require(:entity_instance).permit(:name, :description, :entity_type_id)
    end

    def delete_old_label
      @entity_instance.delete_label
    end

end

app/helpers/entity_instance_helper.rb
module EntityInstanceHelper
end

app/views/entity_instances/_form.html.haml
= form_for @entity_instance, :html => { :class => "form-horizontal" } do |f|
  - if @entity_instance.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      %h2
        = pluralize(@entity_instance.errors.count, "error")
        prohibited
        this entity_instance from being saved:
      %ul
        - @entity_instance.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, t('entity_instances.attributes.name'), :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, :class => "form-control"
  .form-group
    = f.label :description, t('entity_instances.attributes.description'), :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :description, :class => "form-control"
  .form-group
    = f.label :entity_type, t('entity_instances.attributes.type'), :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :entity_type, :class => "form-control typeahead", value: @type
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"
:javascript
  var engine = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {"url":'/entity_instances/autocomplete_type?query=%QUERY'}
  });

  engine.initialize();

  $(".typeahead").typeahead({
    "highlight": true
  },
  {
    minLength: 1,
    name: 'dataset',
    displayKey: 'name',
    "source": engine.ttAdapter()
  })

app/views/entity_instances/edit.html.haml
%h1= t('helpers.edit') + ' '  + t('entity_instances.model_name')
= render 'form'
= link_to t('helpers.back'), entity_instances_path

app/views/entity_instances/index.html.haml
%h1= t('entity_instances.models_name')
%table.table
  %tr
    %th= t('entity_instances.attributes.name')
    %th= t('entity_instances.attributes.description')
    %th{:colspan => "3"}
  - @entity_instances.each do |entity_instance|
    %tr
      %td=link_to entity_instance.name, entity_instance_path(entity_instance)
      %td= entity_instance.description
      -if can? :manage, EntityInstance
        %td= link_to t('helpers.edit'), edit_entity_instance_path(entity_instance)
        %td= link_to t('helpers.destroy'), entity_instance_path(entity_instance), |
            method: :delete, data: { confirm: 'Are you sure?' }       |
= paginate @entity_instances
= link_to t('entity_instances.new') + ' '  + t('entity_instances.model_name'), new_entity_instance_path if can? :manage, EntityInstance

app/views/entity_instances/new.html.haml
%h1= t('entity_instances.new') + ' '  + t('entity_instances.model_name')
= render 'form'
= link_to t('helpers.back'), entity_instances_path

app/views/entity_instances/preview.html.haml
.page-header
  %h1= t('entity_instances.model_name')
%dl.dl-horizontal
  %dt= t('entity_instances.attributes.name')
  %dd= @entity_instance.name
  %dt= t('entity_instances.attributes.description')
  %dd= @entity_instance.description
  %dt= t('entity_instances.attributes.graph_id')
  %dd= @entity_instance.node_id
  %dt= t('entity_instances.attributes.type')
  %dd= @entity_type.name
  %dt= t('entity_instances.attributes.creator')
  %dd= @entity_instance.user.initials
.page-header
  %h1= t('relationships.models_name')
.col-md-6
  %h3= t('relationships.attributes.entity_instance_from')
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t('relationships.attributes.name')
          %th= t('relationships.attributes.entity_instance_to')
          %th= t('relationships.attributes.type')
      %tbody
        = content_tag_for(:tr, @entity_instance.relationships_from) do |relationship|
          %td= link_to relationship.name, relationship
          %td= link_to relationship.entity_to.name, relationship.entity_to
          %td= relationship.relationship_type.name
.col-md-6
  %h3= t('relationships.attributes.entity_instance_to')
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t('relationships.attributes.name')
          %th= t('relationships.attributes.entity_instance_from')
          %th= t('relationships.attributes.type')
      %tbody
        = content_tag_for(:tr, @entity_instance.relationships_to) do |relationship|
          %td= link_to relationship.name, relationship
          %td= link_to relationship.entity_from.name, relationship.entity_from
          %td= relationship.relationship_type.name

app/views/entity_instances/show.html.haml
.page-header
  = link_to entity_instances_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    = t('helpers.back')
  -if can? :manage, EntityInstance
    = link_to edit_entity_instance_path(@entity_instance), :class => 'btn btn-primary' do
      %span.glyphicon.glyphicon-pencil
      = t('helpers.edit')
  %h1= t('entity_instances.model_name')
%dl.dl-horizontal
  %dt= t('entity_instances.attributes.name')
  %dd= @entity_instance.name
  %dt= t('entity_instances.attributes.description')
  %dd= @entity_instance.description
  %dt= t('entity_instances.attributes.graph_id')
  %dd= @entity_instance.node_id
  %dt= t('entity_instances.attributes.type')
  %dd= @entity_type.name
  %dt= t('entity_instances.attributes.creator')
  %dd= @entity_instance.user.initials
.page-header
  %h1= t('relationships.models_name')
.col-md-6
  %h3= t('relationships.attributes.entity_instance_from')
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t('relationships.attributes.name')
          %th= t('relationships.attributes.entity_instance_to')
          %th= t('relationships.attributes.type')
      %tbody
        = content_tag_for(:tr, @entity_instance.relationships_from) do |relationship|
          %td= link_to relationship.name, relationship
          %td= link_to relationship.entity_to.name, relationship.entity_to
          %td= relationship.relationship_type.name
.col-md-6
  %h3= t('relationships.attributes.entity_instance_to')
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t('relationships.attributes.name')
          %th= t('relationships.attributes.entity_instance_from')
          %th= t('relationships.attributes.type')
      %tbody
        = content_tag_for(:tr, @entity_instance.relationships_to) do |relationship|
          %td= link_to relationship.name, relationship
          %td= link_to relationship.entity_from.name, relationship.entity_from
          %td= relationship.relationship_type.name