config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    resources :admintools, only: :index do
      post :clear, on: :collection
      post 'addrows', on: :collection
      post 'upload', on: :collection
      post 'upload_yaml', on: :collection
      get 'download', on: :collection
      get 'download_full', on: :collection
    end
    devise_for :users, :controllers => { invitations: 'invitations'}
    resources :entity_instances do 
      get :autocomplete, on: :collection
      get :autocomplete_type, on: :collection
      get :preview
      
    end
    resources :users

    resources :suggest_relationships

    resources :admintools
    
    resources :relationships do
      resources :relationship_bits
      get :autocomplete_type, on: :collection
      get :preview
    end

    resources :searches do
      get :search_history, on: :collection
      get :search, on: :collection
      get :root, on: :collection
      get :load_info, on: :member
    end

    get '*unmatched_route', to: 'application#raise_not_found'

  end
  root 'searches#root'

  get '/:locale' => 'searches#root'
 
  

end

app/models/relationship_bit.rb
# == Schema Information
#
# Table name: relationship_bits
#
#  id              :integer          not null, primary key
#  url             :text
#  comment         :text
#  fulltext        :text
#  relationship_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class RelationshipBit < ActiveRecord::Base
  belongs_to :relationship
end

app/controllers/relationship_bits_controller.rb
class RelationshipBitsController < ApplicationController
  authorize_resource
  before_action :set_relationship

  def index
    @relationship_bits = @relationship.relationship_bits.page(params[:page]).per(25)
  end

  def create
    @relationship_bit = @relationship.relationship_bits.create(relationship_bit_params)
    redirect_to relationship_relationship_bits_path(@relationship)
  end

  def destroy
    @relationship_bit = @relationship.relationship_bits.find(params[:id])
    @relationship_bit.destroy
    redirect_to relationship_path(@relationship)
  end
 
  private

    def set_relationship
      @relationship = Relationship.find(params[:relationship_id])
    end

    def relationship_bit_params
      params.require(:relationship_bit).permit(:url, :comment, :fulltext)
    end
end

app/helpers/relationship_bits_helper.rb
module RelationshipBitsHelper
end

app/views/relationship_bits/_form.html.haml
= form_for([@relationship, @relationship.relationship_bits.build], :html => { :class => "form-horizontal" }) do |f|
  .form-group
    = f.label :url, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :url, :class => "form-control"
  .form-group
    = f.label :comment, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :comment, :class => "form-control"
  .form-group
    = f.label :fulltext, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :fulltext, :class => "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/relationship_bits/_relationship_bit.html.haml
%p
  %strong URL:
  = relationship_bit.url
%p
  %strong Comment:
  = relationship_bit.comment
%p
  %strong Full text:
  = relationship_bit.fulltext
%p
  = link_to 'Destroy Relationship Bit', [relationship_bit.relationship, relationship_bit], |
    method: :delete,                                                                       |
    data: { confirm: 'Are you sure?' }                                                     |

app/views/relationship_bits/index.html.haml
-if can? :manage, Relationship
  %h2 Add a relationship bit:
  = render "form" 
.page-header
  %h1 Listing relationship bits for @relationship.name
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Url
        %th Comment
        %th Full text
        %th
        %th
    %tbody
      = content_tag_for(:tr, @relationship_bits) do |relationship_bit|
        %td= relationship_bit.url
        %td= relationship_bit.comment
        %td= relationship_bit.fulltext
        %td= link_to 'Edit', edit_relationship_relationship_bit_path(@relationship, relationship_bit)
        %td= link_to 'Destroy', relationship_relationship_bit_path(@relationship, relationship_bit), method: :delete, data: { confirm: 'Are you sure?' }
= paginate @relationship_bits, theme: 'twitter-bootstrap-3', pagination_class: "pagination-small pagination-centered"