config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    resources :admintools, only: :index do
      post :clear, on: :collection
      post 'addrows', on: :collection
      post 'upload', on: :collection
      post 'upload_yaml', on: :collection
      get 'download', on: :collection
      get 'download_full', on: :collection
    end
    devise_for :users, :controllers => { invitations: 'invitations'}
    resources :entity_instances do 
      get :autocomplete, on: :collection
      get :autocomplete_type, on: :collection
      get :preview
      
    end
    resources :users

    resources :suggest_relationships

    resources :admintools
    
    resources :relationships do
      resources :relationship_bits
      get :autocomplete_type, on: :collection
      get :preview
    end

    resources :searches do
      get :search_history, on: :collection
      get :search, on: :collection
      get :root, on: :collection
      get :load_info, on: :member
    end

    get '*unmatched_route', to: 'application#raise_not_found'

  end
  root 'searches#root'

  get '/:locale' => 'searches#root'
 
  

end

app/views/layouts/_admin_links.html.haml
%li{class:  (params[:controller]=~/\Aadmintool/) ? 'active' : ''}= link_to t('admin_pages.titles.admin_tools'), admintools_path

app/views/layouts/_header.html.haml
.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Semasearch", root_path, class: 'navbar-brand'
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{class:  current_page?(root_path) ? 'active' : ''}= link_to t('page_titles.home'), root_path
        %li{class:  params[:controller]=~/\Aentity_instances/ ? 'active' : ''}= link_to t('page_titles.entities'), entity_instances_path
        %li{class:  params[:controller]=~/\Arelationships/ ? 'active' : ''}= link_to t('page_titles.relationships'), relationships_path
        %li{class:  params[:controller]=~/\Asuggest_relationships/ ? 'active' : ''}= link_to t('page_titles.suggest'), suggest_relationships_path
        - if can? :manage, :all
          = render 'layouts/admin_links'
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Eng", locale: "en"
        %li= link_to "Ukr", locale: "uk"
        %li{class:  (params[:controller]=~/\Ausers/) && (params[:action]=~/\Ashow/) ? 'active' : ''}= link_to current_user.initials, user_path(current_user)
        %li= link_to t('page_titles.logout'), destroy_user_session_path, :method => :delete
  / /.nav-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "#{content_for?(:title) ? content_for(:title) + " - " + t('page_titles.home_title') : t('page_titles.home_title')}"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header" if current_user
    .container.theme-showcase{:role => "main"}
      = render 'shared/flash_messages' unless flash.empty?
      = yield
    = render "layouts/footer"